# Generated by Django 5.1.3 on 2024-12-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Boss', 'Boss'), ('Employee', 'Employee')], default='Employee', max_length=20),
        ),
    ]
