# Generated by Django 5.1.3 on 2025-01-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nip',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
