# Generated by Django 5.1.3 on 2025-01-04 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_client_nip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('vacation_id', models.AutoField(primary_key=True, serialize=False)),
                ('vacation_date', models.DateField()),
                ('duration', models.DecimalField(decimal_places=1, default=8, max_digits=4)),
                ('comments', models.TextField(blank=True, null=True)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
