# Generated by Django 5.1.3 on 2025-01-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED')], default='PENDING', max_length=20),
        ),
    ]
