# Generated by Django 5.1.3 on 2025-01-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_vacation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED')], max_length=20),
        ),
    ]
