# Generated by Django 5.1.3 on 2025-01-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('VACATION', 'VACATION'), ('TASK', 'TASK'), ('PROJECT', 'PROJECT'), ('PHASE', 'PHASE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20),
        ),
    ]
