# Generated by Django 5.1.3 on 2025-02-04 15:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_notification_type_alter_vacation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='vacation_group_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='nip',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='postcode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='street',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('VACATION', 'VACATION'), ('TASK', 'TASK'), ('PROJECT', 'PROJECT'), ('PHASE', 'PHASE'), ('USER', 'USER'), ('CLIENT', 'CLIENT')], max_length=50),
        ),
    ]
