# Generated by Django 5.1.3 on 2025-02-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_vacation_vacation_group_id_alter_client_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='type',
            field=models.CharField(choices=[('ANNUAL', 'Urlop wypoczynkowy'), ('ON_DEMAND', 'Urlop na żądanie'), ('MATERNITY', 'Urlop macierzyński'), ('PATERNITY', 'Urlop ojcowski'), ('PARENTAL', 'Urlop rodzicielski'), ('CHILDCARE', 'Urlop wychowawczy'), ('UNPAID', 'Urlop bezpłatny'), ('SPECIAL', 'Urlop okolicznościowy'), ('TRAINING', 'Urlop szkoleniowy'), ('HEALTH', 'Urlop zdrowotny')], default='UNPAID', max_length=20),
        ),
    ]
