# Generated by Django 5.1.3 on 2025-02-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_bank_account_user_contract_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contract_type',
            field=models.CharField(choices=[('Boss', 'Boss'), ('Employee', 'Employee')], default='EMPLOYMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Mężczyzna'), ('F', 'Kobieta'), ('I', 'Inna')], max_length=1, null=True),
        ),
    ]
