# Generated by Django 5.1.3 on 2025-02-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_contract_type_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contract_type',
            field=models.CharField(choices=[('EMPLOYMENT', 'Umowa o pracę'), ('CONTRACT', 'Umowa zlecenie'), ('MANDATE', 'Umowa o dzieło'), ('B2B', 'Umowa B2B')], default='EMPLOYMENT', max_length=20),
        ),
    ]
