version: '3.8'

services:
    postgres:
        image: postgres:13
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data


    backend:
        build:
            context: ./backend
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./backend:/app
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        networks:
            - backend
            - frontend

    frontend:
        build:
            context: ./frontend
        ports:
            - "3000:80"  # Mapujemy port 80 w kontenerze na port 3000 na hoście
        depends_on:
            - backend
        networks:
            - frontend

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        ports:
            - "5050:80"
        depends_on:
            - postgres
        networks:
            - backend


volumes:
    postgres_data:
    pgadmin_data:

networks:
    backend:
    frontend: